#SERVER
SERVER_PORT: 8089
ACTIVE_PROFILE: dev

#DATABASE
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: root
POSTGRES_SQL_DB: sineb_rbdd
POSTGRES_SQL_PORT: 5432


