server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client.service-url:
    defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
          replication-factor: 1
      bindings:
         civility-out-0:
           destination: civility
         pays-out-0:
           destination: pays
         type-structure-out-0:
           destination: type-structure
         type-compte-out-0:
          destination: type-compte
  jpa:
    properties:
          org.hibernate.envers.cleanup_strategy: none
          hibernate:
            format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  application:
    name: ddb-service
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sineb_ddb
    username: postgres
    password: root
  sql:
    init:
      mode: never

rsa:
  public-key: classpath:certs/public.pem




