#SERVER
SERVER_PORT: 8082
ACTIVE_PROFILE: dev

#DATABASE
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: root
POSTGRES_SQL_DB: sineb_admin
POSTGRES_SQL_PORT: 5432


