version : "3.9"
services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - my-server-net

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controllers=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - my-server-net
    depends_on:
      - zoo1

  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controllers=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - my-server-net
    depends_on:
      - zoo1


  kafka3:
    image: confluentinc/cp-kafka:7.3.2
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controllers=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - my-server-net
    depends_on:
      - zoo1

  discovery-service:
    container_name: discovery-service
    image: discovery-service:code
    ports:
      - "8761:8761"
    networks:
      - my-server-net

  gateway-service:
    container_name: gateway-service
    image: gateway-service:code
    ports:
      - "8888:8888"
    environment:
      - EUREKA_SERVER = discovery-service:8761/
    networks:
      - my-server-net
    depends_on:
        - discovery-service

  security-service:
    container_name: security-service
    image: security-service:code
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER = discovery-service:8761/
    networks:
      - my-server-net
    depends_on:
      - discovery-service

  identity-service:
    container_name: identity-service
    image: identity-service:code
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER = discovery-service:8761/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS= kafka1:9092,kafka2:9093,kafka3:9094
    networks:
      - my-server-net
    depends_on:
      - discovery-service
      - kafka1
      - kafka2
      - kafka3

  mail-service:
    container_name: mail-service
    image: mail-service:code
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER = discovery-service:8761/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS= kafka1:9092,kafka2:9093,kafka3:9094
    networks:
      - my-server-net
    depends_on:
      - discovery-service
      - kafka1
      - kafka2
      - kafka3
networks:
  my-server-net:
    name: sineb-server-net