#SERVER
SERVER_PORT: 8085
ACTIVE_PROFILE: prod

#DATABASE
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: root
POSTGRES_SQL_DB: sineb_demande
POSTGRES_SQL_PORT: 5432
